/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pedro_imagefilter_AndroidImageFilter */

#ifndef _Included_com_pedro_imagefilter_AndroidImageFilter
#define _Included_com_pedro_imagefilter_AndroidImageFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pedro_imagefilter_AndroidImageFilter
 * Method:    grayScale
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_pedro_imagefilter_AndroidImageFilter_grayScale
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_pedro_imagefilter_AndroidImageFilter
 * Method:    sepia
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_pedro_imagefilter_AndroidImageFilter_sepia
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_pedro_imagefilter_AndroidImageFilter
 * Method:    negative
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_pedro_imagefilter_AndroidImageFilter_negative
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_pedro_imagefilter_AndroidImageFilter
 * Method:    redScale
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_pedro_imagefilter_AndroidImageFilter_redScale
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_pedro_imagefilter_AndroidImageFilter
 * Method:    blueScale
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_pedro_imagefilter_AndroidImageFilter_blueScale
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_pedro_imagefilter_AndroidImageFilter
 * Method:    greenScale
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_pedro_imagefilter_AndroidImageFilter_greenScale
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_pedro_imagefilter_AndroidImageFilter
 * Method:    whiteBalance
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_pedro_imagefilter_AndroidImageFilter_whiteBalance
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
